<?php

namespace Database\Seeders;

use App\Models\Brand;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $columns = [];


        $columns[] = ['characteristic_id' => 5, 'name' => 'Accelera', 'slug' => 'accelera'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Achilles', 'slug' => 'achilles'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Advance', 'slug' => 'advance'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Aeolus', 'slug' => 'aeolus'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Agate', 'slug' => 'agate'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Alliance', 'slug' => 'alliance'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Altenzo', 'slug' => 'altenzo'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Amberstone', 'slug' => 'amberstone'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'America', 'slug' => 'america'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Amtel', 'slug' => 'amtel'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Annaite', 'slug' => 'annaite'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Ansu', 'slug' => 'ansu'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Antares', 'slug' => 'antares'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Antyre', 'slug' => 'antyre'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Aotai', 'slug' => 'aotai'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Aoteli', 'slug' => 'aoteli'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Aplus', 'slug' => 'aplus'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Apollo', 'slug' => 'apollo'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Arcron', 'slug' => 'arcron'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Arivo', 'slug' => 'arivo'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Armforce', 'slug' => 'armforce'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Armour', 'slug' => 'armour'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Armstrong', 'slug' => 'armstrong'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Artum', 'slug' => 'artum'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Atf', 'slug' => 'atf'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Atlas', 'slug' => 'atlas'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'A5tturo', 'slug' => 'atturo'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Aufine', 'slug' => 'aufine'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Aurora', 'slug' => 'aurora'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Austone', 'slug' => 'austone'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Austyre', 'slug' => 'austyre'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Autogrip', 'slug' => 'autogrip'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Autoguard', 'slug' => 'autoguard'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Avatyre', 'slug' => 'avatyre'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Avon', 'slug' => 'avon'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Barkley', 'slug' => 'barkley'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Bars', 'slug' => 'bars'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Barum', 'slug' => 'barum'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'BCT', 'slug' => 'bct'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Benton', 'slug' => 'benton'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Bestrich', 'slug' => 'bestrich'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'BGFoodrich', 'slug' => 'bfgoodrich'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'BKT', 'slug' => 'bkt'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Blacklion', 'slug' => 'blacklion'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Blackstone', 'slug' => 'blackstone'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Bontyre', 'slug' => 'bontyre'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Boto', 'slug' => 'boto'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Brasa', 'slug' => 'brasa'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Bridgestone', 'slug' => 'bridgestone'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Briway', 'slug' => 'briway'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Cachland', 'slug' => 'cachland'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Ceat', 'slug' => 'ceat'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Centara', 'slug' => 'centara'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Changfeng', 'slug' => 'changfeng'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Chaoyang', 'slug' => 'chaoyang'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Chengshan', 'slug' => 'chengshan'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Collins', 'slug' => 'collins'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Comforser', 'slug' => 'comforser'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Compasal', 'slug' => 'compasal'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Compass', 'slug' => 'compass'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Constancy', 'slug' => 'constancy'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Continental', 'slug' => 'continental'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Contyre', 'slug' => 'contyre'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Cooper', 'slug' => 'cooper'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Copartner', 'slug' => 'copartner'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Cordiant', 'slug' => 'cordiant'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Cratos', 'slug' => 'cratos'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Crossleader', 'slug' => 'crossleader'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Crosswind', 'slug' => 'crosswind'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Crown', 'slug' => 'crown'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'CST', 'slug' => 'cst'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'CTM', 'slug' => 'ctm'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Cultor', 'slug' => 'cultor'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Daewoo Tires', 'slug' => 'daewoo-tires'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Davanti', 'slug' => 'davanti'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Dayton', 'slug' => 'dayton'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Dean', 'slug' => 'dean'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Debica', 'slug' => 'debica'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Deestone', 'slug' => 'deestone'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Deli', 'slug' => 'deli'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Delinte', 'slug' => 'delinte'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Dextero', 'slug' => 'dextero'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Diamondback', 'slug' => 'diamondback'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Dick Cepek', 'slug' => 'dick-cepek'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Diplomat', 'slug' => 'diplomat'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Dmack', 'slug' => 'dmack'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Double Coin', 'slug' => 'double-coin'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Double King', 'slug' => 'double-king'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Double Road', 'slug' => 'double-road'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Doublestar', 'slug' => 'doublestar'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Doupro', 'slug' => 'doupro'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Drivemaster', 'slug' => 'drivemaster'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Dunlop', 'slug' => 'dunlop'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Duramax', 'slug' => 'duramax'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Duraturn', 'slug' => 'duraturn'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Duro', 'slug' => 'duro'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Durun', 'slug' => 'durun'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Dynamic', 'slug' => 'dynamic'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Effiplus', 'slug' => 'effiplus'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Estrada', 'slug' => 'estrada'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Evergreen', 'slug' => 'evergreen'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Everton', 'slug' => 'everton'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Falken', 'slug' => 'falken'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Farmer', 'slug' => 'farmer'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Farm Master', 'slug' => 'farm-master'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Farroad', 'slug' => 'farroad'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Fastwear', 'slug' => 'fastwear'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Fate', 'slug' => 'fate'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Federal', 'slug' => 'federal'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Fenix', 'slug' => 'fenix'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Fesite', 'slug' => 'fesite'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Firelion', 'slug' => 'firelion'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Firemax', 'slug' => 'firemax'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Firenza', 'slug' => 'firenza'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Firestone', 'slug' => 'firestone'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'FirstStop', 'slug' => 'firststop'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Fisk', 'slug' => 'fisk'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Force', 'slug' => 'force'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Forerunner', 'slug' => 'forerunner'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Formula', 'slug' => 'formula'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Fortuna', 'slug' => 'fortuna'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Fortune', 'slug' => 'fortune'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Fronway', 'slug' => 'fronway'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Fulda', 'slug' => 'fulda'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Fullrun', 'slug' => 'fullrun'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Fullway', 'slug' => 'fullway'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Fuzion', 'slug' => 'fuzion'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Galaxia', 'slug' => 'galaxia'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Galaxy', 'slug' => 'galaxy'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'General Tire', 'slug' => 'general-tire'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Geostar', 'slug' => 'geostar'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Ginell', 'slug' => 'ginell'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Gislaved', 'slug' => 'gislaved'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'globe-star', 'slug' => 'Globe Star'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Glob Gum', 'slug' => 'glob-gum'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'GM Rover', 'slug' => 'gm-rover'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Goalstar', 'slug' => 'goalstar'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Goform', 'slug' => 'goform'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Gold Dove', 'slug' => 'gold-dove'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Goldpartner', 'slug' => 'goldpartner'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Goldshield', 'slug' => 'goldshield'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Goldway', 'slug' => 'goldway'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Goodfriend', 'slug' => 'goodfriend'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Goodride', 'slug' => 'goodride'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Goodtyre', 'slug' => 'goodtyre'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Goodyear', 'slug' => 'goodyear'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Greatway', 'slug' => 'greatway'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Greckster', 'slug' => 'greckster'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Green Dragon', 'slug' => 'green-dragon'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Green Way', 'slug' => 'green-way'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Greforce', 'slug' => 'greforce'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Gremax', 'slug' => 'gremax'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Grenlander', 'slug' => 'grenlander'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'GRI', 'slug' => 'gri'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Gripmax', 'slug' => 'gripmax'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'GTK', 'slug' => 'gtk'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'GT Radial', 'slug' => 'gt-radial'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Gumi Nira', 'slug' => 'gumi-nira'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Habilead', 'slug' => 'habilead'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Haida', 'slug' => 'haida'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Hankook', 'slug' => 'hankook'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Hanksugi', 'slug' => 'hanksugi'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'HappyRoad', 'slug' => 'happyroad'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Headway', 'slug' => 'headway'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Heidenau', 'slug' => 'heidenau'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Hercules', 'slug' => 'hercules'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Hifly', 'slug' => 'hifly'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Hilo', 'slug' => 'hilo'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Honour', 'slug' => 'honour'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Horizon', 'slug' => 'horizon'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'HunterRoad', 'slug' => 'hunterroad'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Ilink', 'slug' => 'ilink'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Imperial', 'slug' => 'imperial'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Infinity', 'slug' => 'infinity'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Inning', 'slug' => 'inning'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Insa Turbo', 'slug' => 'insa-turbo'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Interstate', 'slug' => 'interstate'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Intertrac', 'slug' => 'intertrac'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Invovic', 'slug' => 'invovic'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Irc Tyre', 'slug' => 'irc-tyre'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Jilutong', 'slug' => 'jilutong'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Jinyu', 'slug' => 'jinyu'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Joyall', 'slug' => 'joyall'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Joyroad', 'slug' => 'joyroad'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Kabat', 'slug' => 'kabat'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Kama', 'slug' => 'kama'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Kapsen', 'slug' => 'kapsen'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Kelly', 'slug' => 'kelly'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Kenda', 'slug' => 'kenda'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Kenex', 'slug' => 'kenex'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Keter', 'slug' => 'keter'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Kinforest', 'slug' => 'kinforest'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Kingrun', 'slug' => 'kingrun'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Kingstar', 'slug' => 'kingstar'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Kleber', 'slug' => 'kleber'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Kormoran', 'slug' => 'kormoran'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Koryo', 'slug' => 'koryo'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Kpatos', 'slug' => 'kpatos'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Kumho Zetum', 'slug' => 'kumho-zetum'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Kunlun', 'slug' => 'kunlun'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Lakesea', 'slug' => 'lakesea'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Lande', 'slug' => 'lande'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Landsail', 'slug' => 'landsail'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Landy', 'slug' => 'landy'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Lanvigator', 'slug' => 'lanvigator'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Lanwoo', 'slug' => 'lanwoo'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Lapponia', 'slug' => 'lapponia'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Lassa', 'slug' => 'lassa'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Laufenn', 'slug' => 'laufenn'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Leao', 'slug' => 'leao'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Lexani', 'slug' => 'lexani'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Ling Long', 'slug' => 'ling-long'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Lionstone', 'slug' => 'lionstone'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Long March', 'slug' => 'long-march'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Lu Shun Da', 'slug' => 'lu-shun-da'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Mabor', 'slug' => 'mabor'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Malhotra', 'slug' => 'malhotra'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Maloya', 'slug' => 'maloya'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Mansory', 'slug' => 'mansory'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Marangoni', 'slug' => 'marangoni'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Marcher', 'slug' => 'marcher'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Marshal', 'slug' => 'marshal'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Mastercraft', 'slug' => 'mastercraft'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Mastersteel', 'slug' => 'mastersteel'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Matador', 'slug' => 'matador'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Matrax', 'slug' => 'matrax'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Maxam', 'slug' => 'maxam'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Maxell', 'slug' => 'maxell'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Maxtrek', 'slug' => 'maxtrek'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Maxxis', 'slug' => 'maxxis'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Mazzini', 'slug' => 'mazzini'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Medalist', 'slug' => 'medalist'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Membat', 'slug' => 'membat'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Mentor', 'slug' => 'mentor'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Metzeler', 'slug' => 'metzeler'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Michelin', 'slug' => 'michelin'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Mickey Thompson', 'slug' => 'mickey-thompson'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Milestone', 'slug' => 'milestone'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Minerva', 'slug' => 'minerva'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Mirage', 'slug' => 'mirage'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Mitas', 'slug' => 'mitas'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Momo', 'slug' => 'momo'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Motrio', 'slug' => 'motrio'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'MRF', 'slug' => 'mrf'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'MRL', 'slug' => 'mrl'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Nama', 'slug' => 'nama'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Nankang', 'slug' => 'nankang'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Neolin', 'slug' => 'neolin'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Neoterra', 'slug' => 'neoterra'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Nereus', 'slug' => 'nereus'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Nexen Roadstone', 'slug' => 'nexenroadstone'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Nitto', 'slug' => 'nitto'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Nokian', 'slug' => 'nokian'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Nordexx', 'slug' => 'nordexx'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Odyking', 'slug' => 'odyking'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Ogreen', 'slug' => 'ogreen'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'OHTSU', 'slug' => 'ohtsu'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Onyx', 'slug' => 'onyx'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Opals', 'slug' => 'opals'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Orium', 'slug' => 'orium'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Otani', 'slug' => 'otani'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Ovation', 'slug' => 'ovation'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Ozka', 'slug' => 'ozka'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Pace', 'slug' => 'pace'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Paxaro', 'slug' => 'paxaro'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Petlas', 'slug' => 'petlas'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Pirelli', 'slug' => 'pirelli'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Platin', 'slug' => 'platin'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Pneumant', 'slug' => 'pneumant'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Point S', 'slug' => 'point-s'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Powertrac', 'slug' => 'powertrac'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Premiorri', 'slug' => 'premiorri'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Presa', 'slug' => 'presa'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Prestivo', 'slug' => 'prestivo'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Primewell', 'slug' => 'primewell'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Primmax', 'slug' => 'primmax'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Radar', 'slug' => 'radar'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Rapid', 'slug' => 'rapid'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Regal', 'slug' => 'regal'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Remington', 'slug' => 'remington'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Riken', 'slug' => 'riken'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Roadcruza', 'slug' => 'roadcruza'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Roadhog', 'slug' => 'roadhog'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Roadlux', 'slug' => 'roadlux'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Roadmarch', 'slug' => 'roadmarch'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Roadmax', 'slug' => 'roadmax'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Roadone', 'slug' => 'roadone'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Roadshine', 'slug' => 'roadshine'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Roadwing', 'slug' => 'roadwing'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Roadx', 'slug' => 'roadx'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Rockblade', 'slug' => 'rockblade'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'RockStone', 'slug' => 'rockstone'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Rosava', 'slug' => 'rosava'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Rotalla', 'slug' => 'rotalla'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Rovelo', 'slug' => 'rovelo'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Royal Black', 'slug' => 'royal-black'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Ruifulai', 'slug' => 'ruifulai'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Runway', 'slug' => 'runway'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Rydanz', 'slug' => 'rydanz'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Saetta', 'slug' => 'saetta'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Safecess', 'slug' => 'safecess'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Safemax', 'slug' => 'safemax'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Saferich', 'slug' => 'saferich'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Sagitar', 'slug' => 'sagitar'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Sailun', 'slug' => 'sailun'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Sailwin', 'slug' => 'sailwin'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Samson', 'slug' => 'samson'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Satoya', 'slug' => 'satoya'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Sava', 'slug' => 'sava'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Security', 'slug' => 'security'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Seha', 'slug' => 'seha'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Seiberling', 'slug' => 'seiberling'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Semperit', 'slug' => 'semperit'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Shimo', 'slug' => 'shimo'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Shinko', 'slug' => 'shinko'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Sierra', 'slug' => 'sierra'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Sigma', 'slug' => 'sigma'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Silverstone', 'slug' => 'silverstone'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Skyfire', 'slug' => 'skyfire'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Snaga', 'slug' => 'snaga'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'SolidPlus', 'slug' => 'solidplus'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Sonar', 'slug' => 'sonar'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Sonny', 'slug' => 'sonny'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Speedways', 'slug' => 'speedways'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Sportiva', 'slug' => 'sportiva'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Sportrak', 'slug' => 'sportrak'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Starco', 'slug' => 'starco'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Starfire', 'slug' => 'starfire'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Starmaxx', 'slug' => 'starmaxx'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Star Performer', 'slug' => 'star-performer'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Strial', 'slug' => 'strial'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Sumitomo', 'slug' => 'sumitomo'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Sumo', 'slug' => 'sumo'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Sunfull', 'slug' => 'sunfull'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Sunitrac', 'slug' => 'sunitrac'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Sunny', 'slug' => 'sunny'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Suntek', 'slug' => 'suntek'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Sunwide', 'slug' => 'sunwide'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Supercargo', 'slug' => 'supercargo'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Superguider', 'slug' => 'superguider'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Superia', 'slug' => 'superia'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Syron', 'slug' => 'syron'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Taidelong', 'slug' => 'taidelong'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Taishan', 'slug' => 'taishan'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Taitong', 'slug' => 'taitong'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Tatko', 'slug' => 'tatko'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Taurus', 'slug' => 'taurus'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'TBB Tires', 'slug' => 'tbb-tires'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Tegrys', 'slug' => 'tegrys'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Teraflex', 'slug' => 'teraflex'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Terraking', 'slug' => 'terraking'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Three-A', 'slug' => 'three-a'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Tigar', 'slug' => 'tigar'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Tomason', 'slug' => 'tomason'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Top Trust', 'slug' => 'top-trust'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Torque', 'slug' => 'torque'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Tosso', 'slug' => 'tosso'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Tourador', 'slug' => 'tourador'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Toyo', 'slug' => 'toyo'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Toyomoto', 'slug' => 'toyomoto'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Tracmax', 'slug' => 'tracmax'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Transking', 'slug' => 'transking'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Transtone', 'slug' => 'transtone'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Trelleborg', 'slug' => 'trelleborg'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Triangle', 'slug' => 'triangle'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Tristar', 'slug' => 'tristar'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Truck24', 'slug' => 'truck24'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Tuneful', 'slug' => 'tuneful'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Tunga', 'slug' => 'tunga'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'TVS', 'slug' => 'tvs'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Tyfoon', 'slug' => 'tyfoon'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Tyrex', 'slug' => 'tyrex'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Unigrip', 'slug' => 'unigrip'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Uniroyal', 'slug' => 'uniroyal'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Valsa', 'slug' => 'valsa'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Vanda', 'slug' => 'vanda'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Veyron', 'slug' => 'veyron'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Viatti', 'slug' => 'viatti'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Viking', 'slug' => 'viking'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Virbac', 'slug' => 'virbac'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'V-Netik', 'slug' => 'v-netik'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Voyager', 'slug' => 'voyager'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Vredestein', 'slug' => 'vredestein'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Wanli', 'slug' => 'wanli'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Waterfall', 'slug' => 'waterfall'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Waynner', 'slug' => 'waynner'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Well Plus', 'slug' => 'well-plus'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Westlake', 'slug' => 'westlake'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Winda', 'slug' => 'winda'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Windforce', 'slug' => 'windforce'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Windpower', 'slug' => 'windpower'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Winrun', 'slug' => 'winrun'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Winterforce', 'slug' => 'winterforce'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Wolfsburg', 'slug' => 'wolfsburg'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Wosen', 'slug' => 'wosen'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Yatone', 'slug' => 'yatone'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Yellow Sea', 'slug' => 'yellow-sea'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Yokohama', 'slug' => 'yokohama'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Zeetex', 'slug' => 'zeetex'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Zeta', 'slug' => 'zeta'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'АШК', 'slug' => 'ashk'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Белшина', 'slug' => 'belshina'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'БШК', 'slug' => 'bshk'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Волтаир', 'slug' => 'voltair'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Воронеж', 'slug' => 'voronezh'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Днепрошина', 'slug' => 'dneproshina'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Киров', 'slug' => 'kirov'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'НкШЗ', 'slug' => 'nkshz'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Омск', 'slug' => 'omsk'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Петрошина', 'slug' => 'petroshina'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Уралшина', 'slug' => 'uralshina'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'ЭллитШина', 'slug' => 'ellitshina'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'Ярославль', 'slug' => 'yaroslavl'];
        $columns[] = ['characteristic_id' => 5, 'name' => 'ЯШЗ', 'slug' => 'yashz'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Adora', 'slug' => 'adora'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Advan', 'slug' => 'advan'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Advanti', 'slug' => 'advanti'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Aez', 'slug' => 'aez'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Aftermarket', 'slug' => 'aftermarket'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Aitl', 'slug' => 'aitl'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Alcar', 'slug' => 'alcar'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Aleks', 'slug' => 'aleks'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Aleks Steel', 'slug' => 'aleks-steel'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Alessio', 'slug' => 'alessio'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Alexrims', 'slug' => 'alexrims'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Allante', 'slug' => 'allante'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Alst', 'slug' => 'alst'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Aluett', 'slug' => 'aluett'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Alutec', 'slug' => 'alutec'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Amati', 'slug' => 'amati'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Angel', 'slug' => 'angel'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Arbet', 'slug' => 'arbet'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Arcasting', 'slug' => 'arcasting'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Argo', 'slug' => 'argo'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Army', 'slug' => 'army'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Atr', 'slug' => 'atr'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Ats', 'slug' => 'ats'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Autom', 'slug' => 'autom'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Avus', 'slug' => 'avus'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Banzai', 'slug' => 'banzai'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Berg', 'slug' => 'berg'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Better', 'slug' => 'better'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Blade', 'slug' => 'blade'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Borbet', 'slug' => 'borbet'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Brock', 'slug' => 'brock'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Buffalo', 'slug' => 'buffalo'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Cam', 'slug' => 'cam'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Carre', 'slug' => 'carre'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Cast Wheels', 'slug' => 'cast-wheels'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'City', 'slug' => 'city'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Cms', 'slug' => 'cms'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Crossfire', 'slug' => 'crossfire'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Darwin', 'slug' => 'darwin'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Dawning', 'slug' => 'dawning'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Dezent', 'slug' => 'dezent'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'DG', 'slug' => 'dg'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Disla', 'slug' => 'disla'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'DJ', 'slug' => 'dj'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Dotz', 'slug' => 'dotz'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Enkei', 'slug' => 'enkei'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Enzo', 'slug' => 'enzo'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Eurodisk', 'slug' => 'eurodisk'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Evolution', 'slug' => 'evolution'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'FBC', 'slug' => 'fbc'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Finest', 'slug' => 'finest'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'FJB', 'slug' => 'fjb'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Fondmetal', 'slug' => 'fondmetal'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'For Wheels', 'slug' => 'for-wheels'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Futek', 'slug' => 'futek'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Gewis Holland', 'slug' => 'gewis-holland'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Giant', 'slug' => 'giant'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Green Line', 'slug' => 'green-line'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'GT', 'slug' => 'gt'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Harp', 'slug' => 'harp'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Hayes Lemmerz', 'slug' => 'hayes-lemmerz'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'HDS', 'slug' => 'hds'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Hi-Tech', 'slug' => 'hi-tech'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'iFree', 'slug' => 'ifree'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Invader', 'slug' => 'invader'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Inzi Aone', 'slug' => 'inzi-aone'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'ITP', 'slug' => 'itp'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Jantsa', 'slug' => 'jantsa'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'JH', 'slug' => 'jh'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'JT', 'slug' => 'jt'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'KFZ', 'slug' => 'kfz'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'KH', 'slug' => 'kh'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Konig', 'slug' => 'konig'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Kormetal', 'slug' => 'kormetal'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Kosei', 'slug' => 'kosei'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Koya', 'slug' => 'koya'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Kyowa', 'slug' => 'kyowa'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Land Rover OEM', 'slug' => 'land-rover-oem'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Landstar', 'slug' => 'landstar'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Lawu', 'slug' => 'lawu'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'League', 'slug' => 'league'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'LegeArtis', 'slug' => 'legeartis'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'LSW', 'slug' => 'lsw'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'MAE Design', 'slug' => 'mae-design'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Magnetto Wheels', 'slug' => 'magnetto-wheels'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Mak', 'slug' => 'mak'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Malata', 'slug' => 'malata'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Mansory', 'slug' => 'mansory'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Marcello', 'slug' => 'marcello'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Maxx', 'slug' => 'maxx'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Mercedes OEM', 'slug' => 'mercedes-oem'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'MIN', 'slug' => 'mim'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Mi-tech', 'slug' => 'mi-tech'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'MKW', 'slug' => 'mkw'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Momo', 'slug' => 'momo'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Monte Fiore', 'slug' => 'monte-fiore'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'MSW', 'slug' => 'msw'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Off Road Wheels', 'slug' => 'off-road-wheels'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Ogreen', 'slug' => 'ogreen'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Onyx', 'slug' => 'onyx'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Original', 'slug' => 'original'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'OZ Racing', 'slug' => 'oz-racing'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'PDW', 'slug' => 'pdw'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Polkar Warmia', 'slug' => 'polkar-warmia'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Primo', 'slug' => 'primo'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'ProCast', 'slug' => 'procast'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'PTH', 'slug' => 'pth'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'R-1', 'slug' => 'r-1'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Race Ready', 'slug' => 'race-ready'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'RC Design', 'slug' => 'rc-design'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Remington', 'slug' => 'remington'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Replay', 'slug' => 'replay'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Replica', 'slug' => 'replica'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Rial', 'slug' => 'rial'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Ronal', 'slug' => 'ronal'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'RS Classic', 'slug' => 'rs-classic'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'RS SUV', 'slug' => 'rs-suv'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'RS Tuning', 'slug' => 'rs-tuning'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'RWP', 'slug' => 'rwp'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'RZT', 'slug' => 'rzt'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Shiba', 'slug' => 'shiba'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Skov Steel Wheels', 'slug' => 'skov-steel-wheels'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Speedline', 'slug' => 'speedline'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Sportmax Racing', 'slug' => 'sportmax-racing'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Sporza', 'slug' => 'sporza'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'SSW', 'slug' => 'ssw'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Steel Arrivo', 'slug' => 'steel-arrivo'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Steel SDT', 'slug' => 'steel-sdt'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Steel Steger', 'slug' => 'steel-steger'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Steel TREBL', 'slug' => 'steel-trebl'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Stilauto', 'slug' => 'stilauto'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Stonewell', 'slug' => 'stonewell'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Storm', 'slug' => 'storm'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Street Art', 'slug' => 'street-art'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Sunrise Wheels', 'slug' => 'sunrise-wheels'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Techline', 'slug' => 'techline'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Tomason', 'slug' => 'tomason'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'TRW', 'slug' => 'trw'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'TSW', 'slug' => 'tsw'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Verde', 'slug' => 'verde'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Vianor', 'slug' => 'vianor'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Viper', 'slug' => 'viper'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Vissol Cast', 'slug' => 'vissol-cast'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Vissol Forged', 'slug' => 'vissol-forged'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'VITELLI', 'slug' => 'vitelli'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Vossen', 'slug' => 'vossen'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Wheels Factory', 'slug' => 'wheels-factory'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Wheel-Top Driver', 'slug' => 'wheel-top-driver'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'WM', 'slug' => 'wm'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Wolf', 'slug' => 'wolf'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'WRC', 'slug' => 'wrc'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'WS Forged', 'slug' => 'ws-forged'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'WSP Italy', 'slug' => 'wsp-italy'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'X-Race', 'slug' => 'x-race'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'X Trike', 'slug' => 'x-trike'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Yokatta Rays', 'slug' => 'yokatta-rays'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'ZD', 'slug' => 'zd'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Zent', 'slug' => 'zent'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'ZF', 'slug' => 'zf'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'ZW', 'slug' => 'zw'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'ZY', 'slug' => 'zy'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'АвтоВАЗ', 'slug' => 'avtovaz'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'ДК', 'slug' => 'dk'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'КиК', 'slug' => 'kik'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Кременчуг', 'slug' => 'kremenchug'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Слад', 'slug' => 'skad'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'Слик', 'slug' => 'slik'];
        $columns[] = ['characteristic_id' => 18, 'name' => 'ХЗДК', 'slug' => 'hzdk'];

            foreach ($columns as $colum => $dataTable) {
                DB::table((new Brand())->getTable())->insert($dataTable);
            }


    }
}
