<?php

namespace Database\Seeders;

use App\Models\CharacteristicValue;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CharacteristicValueSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $columns = [];

        $columns[] = ['characteristic_id' => 4, 'name' => 'зимния', 'slug' => 'zimnie', 'language' => 'ru'];
        $columns[] = ['characteristic_id' => 4, 'name' => 'зимова', 'slug' => 'zimovi', 'language' => 'ua'];
        $columns[] = ['characteristic_id' => 4, 'name' => 'летние', 'slug' => 'letnie', 'language' => 'ru'];
        $columns[] = ['characteristic_id' => 4, 'name' => 'літні', 'slug' => 'litni', 'language' => 'ua'];
        $columns[] = ['characteristic_id' => 4, 'name' => 'всесезонные', 'slug' => 'vsesezonnye', 'language' => 'ru'];
        $columns[] = ['characteristic_id' => 4, 'name' => 'всесезонні', 'slug' => 'vesezonni', 'language' => 'ua'];
        $columns[] = ['characteristic_id' => 4, 'name' => 'зимния', 'slug' => 'zimnie', 'language' => 'ru'];
        $columns[] = ['characteristic_id' => 4, 'name' => 'зимова', 'slug' => 'zimovi', 'language' => 'ua'];
        $columns[] = ['characteristic_id' => 4, 'name' => 'летние', 'slug' => 'letnie', 'language' => 'ru'];
        $columns[] = ['characteristic_id' => 4, 'name' => 'літні', 'slug' => 'litni', 'language' => 'ua'];
        $columns[] = ['characteristic_id' => 4, 'name' => 'всесезонные', 'slug' => 'vsesezonnye', 'language' => 'ru'];
        $columns[] = ['characteristic_id' => 4, 'name' => 'всесезонні', 'slug' => 'vesezonni', 'language' => 'ua'];
        $columns[] = ['characteristic_id' => 4, 'name' => 'зимние шипованные', 'slug' => 'zimnie-shipovannye', 'language' => 'ru'];
        $columns[] = ['characteristic_id' => 4, 'name' => 'зимові шиповані', 'slug' => 'zimovi-shipovani', 'language' => 'ua'];
        $columns[] = ['characteristic_id' => 4, 'name' => 'зимние без шипа', 'slug' => 'zimnie-bez-shipa', 'language' => 'ru'];
        $columns[] = ['characteristic_id' => 4, 'name' => 'зимові без шипа', 'slug' => 'zimovi-bez-shipa', 'language' => 'ua'];
        $columns[] = ['characteristic_id' => 4, 'name' => 'зимние под шипы', 'slug' => 'zimnie-pod-shipy', 'language' => 'ru'];
        $columns[] = ['characteristic_id' => 4, 'name' => 'зимові під шипи', 'slug' => 'zimovi-pid-shipi', 'language' => 'ua'];
        $columns[] = ['characteristic_id' => 1, 'name' => '2.00', 'slug' => 'w2-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '2.25', 'slug' => 'w2-25', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '2.50', 'slug' => 'w2-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '2.75', 'slug' => 'w2-75', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '3.00', 'slug' => 'w3-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '3.25', 'slug' => 'w3-25', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '3.50', 'slug' => 'w3-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '3.75', 'slug' => 'w3-75', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '4.00', 'slug' => 'w4-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '4.10', 'slug' => 'w4-10', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '4.25', 'slug' => 'w4-25', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '4.50', 'slug' => 'w4-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '4.60', 'slug' => 'w4-60', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '5.00', 'slug' => 'w5-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '5.10', 'slug' => 'w5-10', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '5.50', 'slug' => 'w5-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '6.00', 'slug' => 'w6-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '6.25', 'slug' => 'w6-25', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '6.40', 'slug' => 'w6-40', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '6.45', 'slug' => 'w6-45', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '6.50', 'slug' => 'w6-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '6.70', 'slug' => 'w6-70', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '6.95', 'slug' => 'w6-95', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '7.00', 'slug' => 'w7-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '7.50', 'slug' => 'w7-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '7.60', 'slug' => 'w-60', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '8.00', 'slug' => 'w8-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '8.15', 'slug' => 'w8-15', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '8.25', 'slug' => 'w8-25', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '8.30', 'slug' => 'w8-30', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '8.40', 'slug' => 'w8-40', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '8.50', 'slug' => 'w8-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '9.00', 'slug' => 'w9-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '9.50', 'slug' => 'w9-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '10.00', 'slug' => 'w10-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '10.50', 'slug' => 'w10-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '11.00', 'slug' => 'w11-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '11.20', 'slug' => 'w11-20', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '11.50', 'slug' => 'w11-20', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '12.00', 'slug' => 'w12-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '12.40', 'slug' => 'w12-40', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '12.50', 'slug' => 'w12-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '13.00', 'slug' => 'w13-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '13.60', 'slug' => 'w13-60', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '14.00', 'slug' => 'w14-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '14.50', 'slug' => 'w14-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '14.90', 'slug' => 'w14-90', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '15.00', 'slug' => 'w15-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '15.50', 'slug' => 'w15-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '16.00', 'slug' => 'w16-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '16.50', 'slug' => 'w16-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '16.60', 'slug' => 'w16-60', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '16.90', 'slug' => 'w16-90', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '17.50', 'slug' => 'w17-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '18.00', 'slug' => 'w18-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '18.40', 'slug' => 'w18-40', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '19.00', 'slug' => 'w19-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '19.50', 'slug' => 'W19-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '20.00', 'slug' => 'W20-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '20.50', 'slug' => 'W20-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '20.80', 'slug' => 'W20-80', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '21.00', 'slug' => 'W21-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '21.30', 'slug' => 'W21-30', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '21.50', 'slug' => 'w21-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '22.00', 'slug' => 'w22-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '23.00', 'slug' => 'w23-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '23.10', 'slug' => 'w23-10', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '23.50', 'slug' => 'w23-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '24.00', 'slug' => 'w24-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '24.50', 'slug' => 'w24-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '25.00', 'slug' => 'w25-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '26', 'slug' => 'w26', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '26.50', 'slug' => 'w26-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '27.00', 'slug' => 'w27-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '28.00', 'slug' => 'w28-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '28.10', 'slug' => 'w28-10', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '29.00', 'slug' => 'w29-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '29.50', 'slug' => 'w29-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '30', 'slug' => 'w30', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '30.50', 'slug' => 'w30-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '31', 'slug' => 'w31', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '32', 'slug' => 'w32', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '33', 'slug' => 'w33', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '34', 'slug' => 'w34', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '35', 'slug' => 'w35', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '36', 'slug' => 'w36', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '37', 'slug' => 'w37', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '38', 'slug' => 'w38', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '38.5', 'slug' => 'w35-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '39', 'slug' => 'w39', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '40', 'slug' => 'w40', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '42', 'slug' => 'w42', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '60', 'slug' => 'w60', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '70', 'slug' => 'w70', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '80', 'slug' => 'w80', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '90', 'slug' => 'w90', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '100', 'slug' => 'w100', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '110', 'slug' => 'w110', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '115', 'slug' => 'w115', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '120', 'slug' => 'w120', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '125', 'slug' => 'w125', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '130', 'slug' => 'w130', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '135', 'slug' => 'w135', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '140', 'slug' => 'w140', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '145', 'slug' => 'w145', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '150', 'slug' => 'w150', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '155', 'slug' => 'w155', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '160', 'slug' => 'w160', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '165', 'slug' => 'w165', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '170', 'slug' => 'w170', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '175', 'slug' => 'w175', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 1, 'name' => '180', 'slug' => 'w180', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '185', 'slug' => 'w185', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 1, 'name' => '190', 'slug' => 'w190', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '195', 'slug' => 'w195', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 1, 'name' => '200', 'slug' => 'w200', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '205', 'slug' => 'w205', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 1, 'name' => '210', 'slug' => 'w210', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '215', 'slug' => 'w215', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 1, 'name' => '220', 'slug' => 'w220', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '225', 'slug' => 'w225', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 1, 'name' => '230', 'slug' => 'w230', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '235', 'slug' => 'w235', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 1, 'name' => '240', 'slug' => 'w240', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '245', 'slug' => 'w245', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 1, 'name' => '250', 'slug' => 'w250', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '255', 'slug' => 'w255', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 1, 'name' => '260', 'slug' => 'w260', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '265', 'slug' => 'w265', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 1, 'name' => '270', 'slug' => 'w270', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '275', 'slug' => 'w275', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '280', 'slug' => 'w280', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '285', 'slug' => 'w285', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '290', 'slug' => 'w290', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '295', 'slug' => 'w295', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '300', 'slug' => 'w300', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '305', 'slug' => 'w305', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '315', 'slug' => 'w315', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '320', 'slug' => 'w320', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '325', 'slug' => 'w325', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '335', 'slug' => 'w335', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '340', 'slug' => 'w340', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '345', 'slug' => 'w345', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '355', 'slug' => 'w355', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '360', 'slug' => 'w360', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '365', 'slug' => 'w365', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '375', 'slug' => 'w375', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '380', 'slug' => 'w380', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '385', 'slug' => 'w385', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '395', 'slug' => 'w395', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '400', 'slug' => 'w400', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '405', 'slug' => 'w405', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '420', 'slug' => 'w420', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '425', 'slug' => 'w425', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '435', 'slug' => 'w435', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '440', 'slug' => 'w440', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '445', 'slug' => 'w445', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '455', 'slug' => 'w455', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '460', 'slug' => 'w460', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '480', 'slug' => 'w480', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '500', 'slug' => 'w500', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '520', 'slug' => 'w520', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '525', 'slug' => 'w525', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '530', 'slug' => 'w530', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '540', 'slug' => 'w540', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '550', 'slug' => 'w550', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '560', 'slug' => 'w560', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '580', 'slug' => 'w580', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '600', 'slug' => 'w600', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '620', 'slug' => 'w620', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '650', 'slug' => 'w650', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '680', 'slug' => 'w680', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '700', 'slug' => 'w700', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '710', 'slug' => 'w710', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '750', 'slug' => 'w750', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '800', 'slug' => 'w800', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '850', 'slug' => 'w850', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '900', 'slug' => 'w900', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '1000', 'slug' => 'w1000', 'language' => '*'];
        $columns[] = ['characteristic_id' => 1, 'name' => '1050', 'slug' => 'w1050', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '0', 'slug' => 'h0', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '4.50', 'slug' => 'h4-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '6.00', 'slug' => 'h6-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '6.50', 'slug' => 'h6-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '7.0', 'slug' => 'h7-0', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '7.10', 'slug' => 'h7-10', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '8.0', 'slug' => 'h8-0', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '8.5', 'slug' => 'h8-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => 15, 'slug' => 'h9', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => 16, 'slug' => 'h10', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '10.5', 'slug' => 'h10-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '11.00', 'slug' => 'h11-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '11.50', 'slug' => 'h11-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '12.00', 'slug' => 'h12-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '12.50', 'slug' => 'h12-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '13', 'slug' => 'h13', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '13.5', 'slug' => 'h13-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => 6, 'slug' => 'h14', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '14.5', 'slug' => 'h14-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '14.5', 'slug' => 'h14-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => 7, 'slug' => 'h15', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '15.5', 'slug' => 'h15-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '16', 'slug' => 'h16', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '18', 'slug' => 'h18', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '18.5', 'slug' => 'h18-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '19', 'slug' => 'h19', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '20', 'slug' => 'h20', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '20.50', 'slug' => 'h20-50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '21', 'slug' => 'h21', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '22', 'slug' => 'h22', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '23', 'slug' => 'h23', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '24', 'slug' => 'h24', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '25', 'slug' => 'h25', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '26', 'slug' => 'h26', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '27', 'slug' => 'h27', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '28', 'slug' => 'h28', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '30', 'slug' => 'h30', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '31', 'slug' => 'h31', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '33', 'slug' => 'h33', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '35', 'slug' => 'h35', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 2, 'name' => '40', 'slug' => 'h40', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '45', 'slug' => 'h45', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 2, 'name' => '50', 'slug' => 'h50', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 2, 'name' => '55', 'slug' => 'h55', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 2, 'name' => '60', 'slug' => 'h60', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 2, 'name' => '65', 'slug' => 'h65', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 2, 'name' => '70', 'slug' => 'h70', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 2, 'name' => '75', 'slug' => 'h75', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 2, 'name' => '80', 'slug' => 'h80', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 2, 'name' => '85', 'slug' => 'h85', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 2, 'name' => '88', 'slug' => 'h88', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '90', 'slug' => 'h90', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '95', 'slug' => 'h95', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '100', 'slug' => 'h100', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '105', 'slug' => 'h105', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '110', 'slug' => 'h110', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '700', 'slug' => 'h700', 'language' => '*'];
        $columns[] = ['characteristic_id' => 2, 'name' => '720', 'slug' => 'h720', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R4', 'slug' => 'r4', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R5', 'slug' => 'r5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R6', 'slug' => 'r6', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R7', 'slug' => 'r7', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R8', 'slug' => 'R8', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R9', 'slug' => 'r9', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R10', 'slug' => 'r10', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R10C', 'slug' => 'r10c', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R11', 'slug' => 'r11', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R12', 'slug' => 'r12', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R12C', 'slug' => 'r12c', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R13', 'slug' => 'r13', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R13C', 'slug' => 'r13c', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R14', 'slug' => 'r14', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R14C', 'slug' => 'r14c', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R14.5', 'slug' => 'r14-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R15', 'slug' => 'r15', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R15C', 'slug' => 'r15c', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R15.3', 'slug' => 'r15-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R15.5', 'slug' => 'r15-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R16', 'slug' => 'r16', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R16.1', 'slug' => 'r16-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R16.5', 'slug' => 'r16-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R17', 'slug' => 'r17', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R17C', 'slug' => 'r17c', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R17.5', 'slug' => 'r17-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R18', 'slug' => 'r18', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R19', 'slug' => 'r19', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R19.5', 'slug' => 'r19-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R20', 'slug' => 'r20', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R21', 'slug' => 'r21', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R22', 'slug' => 'r22', 'language' => '*', 'popular' => 1];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R22.5', 'slug' => 'r22-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R23', 'slug' => 'r23', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R24', 'slug' => 'r24', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R24.5', 'slug' => 'r24-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R25', 'slug' => 'r25', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R26', 'slug' => 'r26', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R26.5', 'slug' => 'r26-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R28', 'slug' => 'r28', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R29', 'slug' => 'r29', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R30', 'slug' => 'r30', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R30.5', 'slug' => 'r30-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R32', 'slug' => 'r32', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R33', 'slug' => 'r33', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R34', 'slug' => 'r34', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R35', 'slug' => 'r35', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R36', 'slug' => 'r36', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R38', 'slug' => 'r38', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R42', 'slug' => 'r42', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R44', 'slug' => 'r44', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R46', 'slug' => 'r46', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R48', 'slug' => 'r48', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R50', 'slug' => 'r50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R52', 'slug' => 'r52', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R54', 'slug' => 'r54', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R470', 'slug' => 'r470', 'language' => '*'];
        $columns[] = ['characteristic_id' => 3, 'name' => 'R490', 'slug' => 'r490', 'language' => '*'];
        $columns[] = ['characteristic_id' => 13, 'name' => 3, 'slug' => 'w3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 13, 'name' => '4', 'slug' => 'w4', 'language' => '*'];
        $columns[] = ['characteristic_id' => 13, 'name' => '4.5', 'slug' => 'w4-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 13, 'name' => '5', 'slug' => 'w5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 13, 'name' => '5.5', 'slug' => 'w5-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 13, 'name' => 12, 'slug' => 'w6', 'language' => '*'];
        $columns[] = ['characteristic_id' => 13, 'name' => '6.5', 'slug' => 'w6-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 13, 'name' => '6.75', 'slug' => 'w6-75', 'language' => '*'];
        $columns[] = ['characteristic_id' => 13, 'name' => 13, 'slug' => 'w7', 'language' => '*'];
        $columns[] = ['characteristic_id' => 13, 'name' => '7.5', 'slug' => 'w7-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 13, 'name' => 14, 'slug' => 'w8', 'language' => '*'];
        $columns[] = ['characteristic_id' => 13, 'name' => '8.25', 'slug' => 'w8-25', 'language' => '*'];
        $columns[] = ['characteristic_id' => 13, 'name' => '8.5', 'slug' => 'w8-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 13, 'name' => 15, 'slug' => 'w9', 'language' => '*'];
        $columns[] = ['characteristic_id' => 13, 'name' => '9.5', 'slug' => 'w9-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 13, 'name' => 16, 'slug' => 'w10', 'language' => '*'];
        $columns[] = ['characteristic_id' => 13, 'name' => '10.5', 'slug' => 'w10-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 13, 'name' => 17, 'slug' => 'w11', 'language' => '*'];
        $columns[] = ['characteristic_id' => 13, 'name' => '11.5', 'slug' => 'w11-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 13, 'name' => '11.75', 'slug' => 'w11-75', 'language' => '*'];
        $columns[] = ['characteristic_id' => 13, 'name' => '12.00', 'slug' => 'w12-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 13, 'name' => '13.00', 'slug' => 'w13-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 13, 'name' => '14.00', 'slug' => 'w14-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 13, 'name' => '16.00', 'slug' => 'w16-00', 'language' => '*'];
        $columns[] = ['characteristic_id' => 12, 'name' => 16, 'slug' => 'r10', 'language' => '*'];
        $columns[] = ['characteristic_id' => 12, 'name' => 10, 'slug' => 'r12', 'language' => '*'];
        $columns[] = ['characteristic_id' => 12, 'name' => '13', 'slug' => 'r13', 'language' => '*'];
        $columns[] = ['characteristic_id' => 12, 'name' => 6, 'slug' => 'r14', 'language' => '*'];
        $columns[] = ['characteristic_id' => 12, 'name' => 6, 'slug' => 'r14', 'language' => '*'];
        $columns[] = ['characteristic_id' => 12, 'name' => 7, 'slug' => 'r15', 'language' => '*'];
        $columns[] = ['characteristic_id' => 12, 'name' => '15.3', 'slug' => 'r15-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 12, 'name' => '16', 'slug' => 'r16', 'language' => '*'];
        $columns[] = ['characteristic_id' => 12, 'name' => '17', 'slug' => 'r17', 'language' => '*'];
        $columns[] = ['characteristic_id' => 12, 'name' => '17.5', 'slug' => 'r17-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 12, 'name' => '18', 'slug' => 'r18', 'language' => '*'];
        $columns[] = ['characteristic_id' => 12, 'name' => '19', 'slug' => 'r19', 'language' => '*'];
        $columns[] = ['characteristic_id' => 12, 'name' => '19.5', 'slug' => 'r19-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 12, 'name' => '20', 'slug' => 'r20', 'language' => '*'];
        $columns[] = ['characteristic_id' => 12, 'name' => '21', 'slug' => 'r21', 'language' => '*'];
        $columns[] = ['characteristic_id' => 12, 'name' => '22', 'slug' => 'r22', 'language' => '*'];
        $columns[] = ['characteristic_id' => 12, 'name' => '22.5', 'slug' => 'r22-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 12, 'name' => '23', 'slug' => 'r23', 'language' => '*'];
        $columns[] = ['characteristic_id' => 12, 'name' => '24', 'slug' => 'r24', 'language' => '*'];
        $columns[] = ['characteristic_id' => 12, 'name' => '28', 'slug' => 'r28', 'language' => '*'];
        $columns[] = ['characteristic_id' => 12, 'name' => '32', 'slug' => 'r32', 'language' => '*'];
        $columns[] = ['characteristic_id' => 12, 'name' => '42', 'slug' => 'r42', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '3x98', 'slug' => 'pcd3x98', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '3x112', 'slug' => 'pcd3x112', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '3x255.5', 'slug' => 'pcd3x255-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '3x256', 'slug' => 'pcd3x256', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '4x98', 'slug' => 'pcd4x98', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '4x98/100', 'slug' => 'pcd4x98-100', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '4x98/108', 'slug' => 'pcd4x98-108', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '4x98/114.3', 'slug' => 'pcd4x98-114-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '4x100', 'slug' => 'pcd4x100', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '4x100/108', 'slug' => 'pcd4x100-108', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '4x100/114.3', 'slug' => 'pcd4x100-114-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '4x108', 'slug' => 'pcd4x108', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '4x110', 'slug' => 'pcd4x110', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '4x112', 'slug' => 'pcd4x112', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '4x114.3', 'slug' => 'pcd4x114-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '4x115', 'slug' => 'pcd4x115', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '4x120', 'slug' => 'pcd4x120', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '4x137', 'slug' => 'pcd4x137', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '4x144', 'slug' => 'pcd4x144', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '4x156', 'slug' => 'pcd4x156', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x98', 'slug' => 'pcd5x98', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x98/100', 'slug' => 'pcd5x98-100', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x98/114.3', 'slug' => 'pcd5x98-114-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x100', 'slug' => 'pcd5x100', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x100/108', 'slug' => 'pcd5x100-108', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x100/110', 'slug' => 'pcd5x100-110', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x100/112', 'slug' => 'pcd5x100-112', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x100/114.3', 'slug' => 'pcd5x100-114-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x105', 'slug' => 'pcd5x105', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x105/110', 'slug' => 'pcd5x105-110', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x105/114.3', 'slug' => 'pcd5x105-114-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x108', 'slug' => 'pcd5x108', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x108/110', 'slug' => 'pcd5x108-110', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x108/112', 'slug' => 'pcd5x108-112', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x108/114.3', 'slug' => 'pcd5x108-114-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x108/115', 'slug' => 'pcd5x108-115', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x110', 'slug' => 'pcd5x110', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x110/112', 'slug' => 'pcd5x110-112', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x110/114.3', 'slug' => 'pcd5x110-114-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x110/120', 'slug' => 'pcd5x110-120', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x112', 'slug' => 'pcd5x112', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x112/114.3', 'slug' => 'pcd5x112-114-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x112/115', 'slug' => 'pcd5x112-115', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x112/118', 'slug' => 'pcd5x112-118', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x112/120', 'slug' => 'pcd5x112-120', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x114', 'slug' => 'pcd5x114', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x114.3', 'slug' => 'pcd5x114-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x114.3/120', 'slug' => 'pcd5x114-3-120', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x114.3/130', 'slug' => 'pcd5x114-3-130', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x114.3/135', 'slug' => 'pcd5x114-3-135', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x115', 'slug' => 'pcd5x115', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x115/118', 'slug' => 'pcd5x115-118', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x118', 'slug' => 'pcd5x118', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x118/130', 'slug' => 'pcd5x118-130', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x120', 'slug' => 'pcd5x120', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x120/130', 'slug' => 'pcd5x120-130', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x127', 'slug' => 'pcd5x127', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x130', 'slug' => 'pcd5x130', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x135', 'slug' => 'pcd5x135', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x135/139.7', 'slug' => 'pcd5x135-139-7', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x139.7', 'slug' => 'pcd5x139-7', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x139.7/150', 'slug' => 'pcd5x139-7-150', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x150', 'slug' => 'pcd5x150', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x160', 'slug' => 'pcd5x160', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '5x165', 'slug' => 'pcd5x165', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '6x114.3', 'slug' => 'pcd6x114-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '6x114.3/139.7', 'slug' => 'pcd6x114-3-139-7', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '6x120', 'slug' => 'pcd6x120', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '6x125', 'slug' => 'pcd6x125', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '6x127', 'slug' => 'pcd6x127', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '6x130', 'slug' => 'pcd6x130', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '6x135', 'slug' => 'pcd6x135', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '6x135/139.7', 'slug' => 'pcd6x135-139-7', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '6x139', 'slug' => 'pcd6x139', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '6x139.7', 'slug' => 'pcd6x139-7', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '6x161', 'slug' => 'pcd6x161', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '6x170', 'slug' => 'pcd6x170', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '6x180', 'slug' => 'pcd6x180', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '6x190', 'slug' => 'pcd6x190', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '6x205', 'slug' => 'pcd6x205', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '6x222', 'slug' => 'pcd6x222', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '6x222.25', 'slug' => 'pcd6x222-25', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '6x245', 'slug' => 'pcd6x245', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '6x245.2', 'slug' => 'pcd6x245-2', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '8x98/100', 'slug' => 'pcd8x98-100', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '8x98/108', 'slug' => 'pcd8x98-108', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '8x98/114.3', 'slug' => 'pcd8x98-114-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '8x100/108', 'slug' => 'pcd8x100-108', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '8x100/114', 'slug' => 'pcd8x100-114', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '8x100/114.3', 'slug' => 'pcd8x100-114-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '8x108/112', 'slug' => 'pcd8x108-112', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '8x108/114.3', 'slug' => 'pcd8x108-114-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '8x165', 'slug' => 'pcd8x165', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '8x165.1', 'slug' => 'pcd8x165-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '8x199', 'slug' => 'pcd8x199', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '8x221', 'slug' => 'pcd8x221', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '8x250', 'slug' => 'pcd8x250', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '8x275', 'slug' => 'pcd8x275', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '9x100', 'slug' => 'pcd9x100', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '10x100', 'slug' => 'pcd10x100', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '10x100/112', 'slug' => 'pcd10x100-112', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '10x100/114.3', 'slug' => 'pcd10x100-114-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '10x108/110', 'slug' => 'pcd10x108-110', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '10x108/112', 'slug' => 'pcd10x108-112', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '10x108/114.3', 'slug' => 'pcd10x108-114-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '10x110', 'slug' => 'pcd10x110', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '10x110/112', 'slug' => 'pcd10x110-112', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '10x110/114.3', 'slug' => 'pcd10x110-114-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '10x112/114.3', 'slug' => 'pcd10x112-114-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '10x112/120', 'slug' => 'pcd10x112-120', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '10x114.3', 'slug' => 'pcd10x114-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '10x114.3/120', 'slug' => 'pcd10x114-3-120', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '10x120/130', 'slug' => 'pcd10x120-130', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '10x139.7/150', 'slug' => 'pcd10x139-7-150', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '10x225', 'slug' => 'pcd10x225', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '10x281', 'slug' => 'pcd10x281', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '10x335', 'slug' => 'pcd10x335', 'language' => '*'];
        $columns[] = ['characteristic_id' => 14, 'name' => '12x135/139.7', 'slug' => 'pcd12x135-139-7', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '0', 'slug' => 'dia0', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '54', 'slug' => 'dia54', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '54.1', 'slug' => 'dia54-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '56', 'slug' => 'dia56', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '56.1', 'slug' => 'dia56-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '56.5', 'slug' => 'dia56-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '56.6', 'slug' => 'dia56-6', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '56.7', 'slug' => 'dia56-7', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '56.56', 'slug' => 'dia56-56', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '57', 'slug' => 'dia57', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '57.1', 'slug' => 'dia57-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '57.6', 'slug' => 'dia57-6', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '58', 'slug' => 'dia58', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '58.1', 'slug' => 'dia58-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '58.5', 'slug' => 'dia58-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '58.6', 'slug' => 'dia58-6', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '59', 'slug' => 'dia59', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '59.5', 'slug' => 'dia59-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '59.6', 'slug' => 'dia59-6', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '60', 'slug' => 'dia60', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '60.1', 'slug' => 'dia60-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '60.2', 'slug' => 'dia60-2', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '60.5', 'slug' => 'dia60-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '61.1', 'slug' => 'dia61-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '63', 'slug' => 'dia63', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '63.1', 'slug' => 'dia63-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '63.3', 'slug' => 'dia63-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '63.4', 'slug' => 'dia63-4', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '63.5', 'slug' => 'dia63-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '63.34', 'slug' => 'dia63-34', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '63.35', 'slug' => 'dia63-35', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '64', 'slug' => 'dia64', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '64.1', 'slug' => 'dia64-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '64.2', 'slug' => 'dia64-2', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '65', 'slug' => 'dia65', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '65.1', 'slug' => 'dia65-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '66', 'slug' => 'dia66', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '66.1', 'slug' => 'dia66-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '66.2', 'slug' => 'dia66-2', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '66.4', 'slug' => 'dia66-4', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '66.5', 'slug' => 'dia66-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '66.6', 'slug' => 'dia66-6', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '66.9', 'slug' => 'dia66-9', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '66.45', 'slug' => 'dia66-45', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '66.56', 'slug' => 'dia66-56', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '67', 'slug' => 'dia67', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '67.1', 'slug' => 'dia67-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '68', 'slug' => 'dia68', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '69', 'slug' => 'dia69', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '69.1', 'slug' => 'dia69-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '69.3', 'slug' => 'dia69-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '70', 'slug' => 'dia70', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '70.1', 'slug' => 'dia70-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '70.2', 'slug' => 'dia70-2', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '70.3', 'slug' => 'dia70-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '70.5', 'slug' => 'dia70-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '70.6', 'slug' => 'dia70-6', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '70.7', 'slug' => 'dia70-7', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '71', 'slug' => 'dia71', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '71.1', 'slug' => 'dia71-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '71.3', 'slug' => 'dia71-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '71.4', 'slug' => 'dia71-4', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '71.5', 'slug' => 'dia71-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '71.6', 'slug' => 'dia71-6', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '72', 'slug' => 'dia72', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '72.1', 'slug' => 'dia72-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '72.2', 'slug' => 'dia72-2', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '72.3', 'slug' => 'dia72-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '72.4', 'slug' => 'dia72-4', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '72.5', 'slug' => 'dia72-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '72.6', 'slug' => 'dia72-6', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '72.56', 'slug' => 'dia72-56', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '73', 'slug' => 'dia73', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '73.1', 'slug' => 'dia73-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '73.2', 'slug' => 'dia73-2', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '74.1', 'slug' => 'dia74-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '75.1', 'slug' => 'dia75-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '76', 'slug' => 'dia76', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '76.1', 'slug' => 'dia76-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '77.7', 'slug' => 'dia77-7', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '77.8', 'slug' => 'dia77-8', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '77.9', 'slug' => 'dia77-9', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '77.77', 'slug' => 'dia77-77', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '78', 'slug' => 'dia78', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '78.1', 'slug' => 'dia78-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '79', 'slug' => 'dia79', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '79.6', 'slug' => 'dia79-6', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '82', 'slug' => 'dia82', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '83', 'slug' => 'dia83', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '84', 'slug' => 'dia84', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '84.1', 'slug' => 'dia84-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '84.2', 'slug' => 'dia84-2', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '86', 'slug' => 'dia86', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '87.1', 'slug' => 'dia87-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '89', 'slug' => 'dia89', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '89.1', 'slug' => 'dia89-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '92.3', 'slug' => 'dia92-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '92.4', 'slug' => 'dia92-4', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '92.5', 'slug' => 'dia92-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '93.1', 'slug' => 'dia93-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '95.3', 'slug' => 'dia95-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '95.5', 'slug' => 'dia95-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '98', 'slug' => 'dia98', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '98.1', 'slug' => 'dia98-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '98.5', 'slug' => 'dia98-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '98.6', 'slug' => 'dia98-6', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '100.1', 'slug' => 'dia100-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '101.5', 'slug' => 'dia101-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '102.2', 'slug' => 'dia102-2', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '106', 'slug' => 'dia106', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '106.1', 'slug' => 'dia106-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '106.2', 'slug' => 'dia106-2', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '106.3', 'slug' => 'dia106-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '106.4', 'slug' => 'dia106-4', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '106.6', 'slug' => 'dia106-6', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '107.5', 'slug' => 'dia107-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '108', 'slug' => 'dia108', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '108.1', 'slug' => 'dia108-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '108.2', 'slug' => 'dia108-2', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '108.3', 'slug' => 'dia108-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '108.4', 'slug' => 'dia108-4', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '108.5', 'slug' => 'dia108-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '108.6', 'slug' => 'dia108-6', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '109.5', 'slug' => 'dia109-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '109.7', 'slug' => 'dia109-7', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '109.8', 'slug' => 'dia109-8', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '110', 'slug' => 'dia110', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '110.1', 'slug' => 'dia110-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '110.2', 'slug' => 'dia110-2', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '110.3', 'slug' => 'dia110-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '110.5', 'slug' => 'dia110-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '111', 'slug' => 'dia111', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '111.1', 'slug' => 'dia111-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '111.2', 'slug' => 'dia111-2', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '112', 'slug' => 'dia112', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '114', 'slug' => 'dia114', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '116.7', 'slug' => 'dia116-7', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '117', 'slug' => 'dia117', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '130', 'slug' => 'dia130', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '130.1', 'slug' => 'dia130-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '130.2', 'slug' => 'dia130-2', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '141', 'slug' => 'dia141', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '161', 'slug' => 'dia161', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '164', 'slug' => 'dia164', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '175', 'slug' => 'dia175', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '176', 'slug' => 'dia176', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '202', 'slug' => 'dia202', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '205', 'slug' => 'dia205', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '221', 'slug' => 'dia221', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '226.5', 'slug' => 'dia226-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '228', 'slug' => 'dia228', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '228.1', 'slug' => 'dia228-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '230', 'slug' => 'dia230', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '250', 'slug' => 'dia250', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '275', 'slug' => 'dia275', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '281', 'slug' => 'dia281', 'language' => '*'];
        $columns[] = ['characteristic_id' => 15, 'name' => '335', 'slug' => 'dia335', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '0', 'slug' => 'et0', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => 2, 'slug' => 'et2', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => 3, 'slug' => 'et3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '4', 'slug' => 'et4', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '5', 'slug' => 'et5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => 12, 'slug' => 'et6', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => 13, 'slug' => 'et7', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => 15, 'slug' => 'et9', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => 16, 'slug' => 'et10', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => 17, 'slug' => 'et11', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => 10, 'slug' => 'et12', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '13', 'slug' => 'et13', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => 6, 'slug' => 'et14', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => 7, 'slug' => 'et15', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '16', 'slug' => 'et16', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '17', 'slug' => 'et17', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '18.5', 'slug' => 'et18-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '19', 'slug' => 'et19', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '19.1', 'slug' => 'et19-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '20', 'slug' => 'et20', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '21', 'slug' => 'et21', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '22', 'slug' => 'et22', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '22.5', 'slug' => 'et22-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '23', 'slug' => 'et23', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '23.5', 'slug' => 'et23-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '24', 'slug' => 'et24', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '25', 'slug' => 'et25', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '26', 'slug' => 'et26', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '27', 'slug' => 'et27', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '27.3', 'slug' => 'et27-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '28', 'slug' => 'et28', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '29', 'slug' => 'et29', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '30', 'slug' => 'et30', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '31', 'slug' => 'et31', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '32', 'slug' => 'et32', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '33', 'slug' => 'et33', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '34', 'slug' => 'et34', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '34.5', 'slug' => 'et34-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '35', 'slug' => 'et35', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '36', 'slug' => 'et36', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '36.5', 'slug' => 'et36-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '37', 'slug' => 'et37', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '37.5', 'slug' => 'et37-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '38', 'slug' => 'et38', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '38.5', 'slug' => 'et38-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '39', 'slug' => 'et39', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '39.5', 'slug' => 'et39-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '40', 'slug' => 'et40', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '40.5', 'slug' => 'et40-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '41', 'slug' => 'et41', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '41.3', 'slug' => 'et41-3', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '41.5', 'slug' => 'et41-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '42', 'slug' => 'et42', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '42.5', 'slug' => 'et42-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '42.7', 'slug' => 'et42-7', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '43', 'slug' => 'et43', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '43.5', 'slug' => 'et43-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '44', 'slug' => 'et44', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '44.5', 'slug' => 'et44-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '45', 'slug' => 'et45', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '45.5', 'slug' => 'et45-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '46', 'slug' => 'et46', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '47', 'slug' => 'et47', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '47.5', 'slug' => 'et47-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '48', 'slug' => 'et48', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '48.5', 'slug' => 'et48-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '49', 'slug' => 'et49', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '49.5', 'slug' => 'et49-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '50', 'slug' => 'et50', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '50.1', 'slug' => 'et50-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '50.5', 'slug' => 'et50-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '50.8', 'slug' => 'et50-8', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '51', 'slug' => 'et51', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '52', 'slug' => 'et52', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '52.5', 'slug' => 'et52-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '53', 'slug' => 'et53', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '54', 'slug' => 'et54', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '55', 'slug' => 'et55', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '55.5', 'slug' => 'et55-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '56', 'slug' => 'et56', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '56.4', 'slug' => 'et56-4', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '57', 'slug' => 'et57', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '58', 'slug' => 'et58', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '59', 'slug' => 'et59', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '60', 'slug' => 'et60', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '61', 'slug' => 'et61', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '62', 'slug' => 'et62', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '63', 'slug' => 'et63', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '64', 'slug' => 'et64', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '65', 'slug' => 'et65', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '66', 'slug' => 'et66', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '67', 'slug' => 'et67', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '68', 'slug' => 'et68', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '69', 'slug' => 'et69', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '70', 'slug' => 'et70', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '71', 'slug' => 'et71', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '75', 'slug' => 'et75', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '83', 'slug' => 'et83', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '96', 'slug' => 'et96', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '102', 'slug' => 'et102', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '105', 'slug' => 'et105', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '106', 'slug' => 'et106', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '108', 'slug' => 'et108', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '115', 'slug' => 'et115', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '116', 'slug' => 'et116', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '117', 'slug' => 'et117', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '120', 'slug' => 'et120', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '121.5', 'slug' => 'et121-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '123', 'slug' => 'et123', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '124', 'slug' => 'et124', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '125', 'slug' => 'et125', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '127', 'slug' => 'et127', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '127.5', 'slug' => 'et127-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '128', 'slug' => 'et128', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '128.5', 'slug' => 'et128-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '132', 'slug' => 'et132', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '132.5', 'slug' => 'et132-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '133', 'slug' => 'et133', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '135', 'slug' => 'et135', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '135.5', 'slug' => 'et135-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '138.5', 'slug' => 'et138-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '140', 'slug' => 'et140', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '142', 'slug' => 'et142', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '143', 'slug' => 'et143', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '146.5', 'slug' => 'et146-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '150', 'slug' => 'et150', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '152', 'slug' => 'et152', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '155', 'slug' => 'et155', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '161', 'slug' => 'et161', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '165', 'slug' => 'et165', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '175', 'slug' => 'et175', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '177.5', 'slug' => 'et177-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '-1', 'slug' => 'et-1', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '-4', 'slug' => 'et-4', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '-5', 'slug' => 'et-5', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '-8', 'slug' => 'et-8', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '-10', 'slug' => 'et-10', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '-12', 'slug' => 'et-12', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '-18', 'slug' => 'et-18', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '-20', 'slug' => 'et-20', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '-25', 'slug' => 'et-25', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '-27', 'slug' => 'et-27', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '-44', 'slug' => 'et-44', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '-45', 'slug' => 'et-45', 'language' => '*'];
        $columns[] = ['characteristic_id' => 16, 'name' => '-46', 'slug' => 'et-46', 'language' => '*'];
        $columns[] = ['characteristic_id' => 17, 'name' => 'Литой', 'slug' => 'litoj', 'language' => 'ru'];
        $columns[] = ['characteristic_id' => 17, 'name' => 'Літий', 'slug' => 'litij', 'language' => 'ua'];
        $columns[] = ['characteristic_id' => 17, 'name' => 'Стальной', 'slug' => 'stalnoj', 'language' => 'ru'];
        $columns[] = ['characteristic_id' => 17, 'name' => 'Сталевий', 'slug' => 'stalevij', 'language' => 'ua'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'A1 - до 5 км/ч', 'slug' => 'is-a1-do-5-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'A2 - до 10 км/ч', 'slug' => 'is-a2-do-10-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'A2/B', 'slug' => 'is-a2b', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'A3 - до 15 км/ч', 'slug' => 'is-a3-do-15-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'A4 - до 20 км/ч', 'slug' => 'is-a4-do-20-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'A5 - до 25 км/ч', 'slug' => 'is-a5-do-25-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'A6 - до 30 км/ч', 'slug' => 'is-a6-do-30-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'A7 - до 35 км/ч', 'slug' => 'is-a7-do-35-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'A8 - до 40 км/ч', 'slug' => 'is-a8-do-40-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'B - до 50 км/ч', 'slug' => 'is-b-do-50-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'C - до 60 км/ч', 'slug' => 'is-c-do-60-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'D - до 65 км/ч', 'slug' => 'is-d-do-65-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'E - до 70 км/ч', 'slug' => 'is-e-do-70-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'F - до 80 км/ч', 'slug' => 'is-f-do-80-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'G - до 90 км/ч', 'slug' => 'is-g-do-90-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'H - до 210 км/ч', 'slug' => 'is-h-do-210-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'J - до 100 км/ч', 'slug' => 'is-j-do-100-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'K - до 110 км/ч', 'slug' => 'is-k-do-110-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'L - до 120 км/ч', 'slug' => 'is-l-do-120-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'M - до 130 км/ч', 'slug' => 'is-m-do-130-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'N - до 140 км/ч', 'slug' => 'is-n-do-140-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'P - до 150 км/ч', 'slug' => 'is-p-do-150-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'Q - до 160 км/ч', 'slug' => 'is-q-do-160-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'R - до 170 км/ч', 'slug' => 'is-r-do-170-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'S - до 180 км/ч', 'slug' => 'is-s-do-180-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'T - до 190 км/ч', 'slug' => 'is-t-do-190-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'V - до 240 км/год', 'slug' => 'is-v-do-240-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'W - до 270 км/год', 'slug' => 'is-w-do-270-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'Y - до 300 км/год', 'slug' => 'is-y-do-300-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'ZR - вище 240 км/год', 'slug' => 'is-zr-svyishe-240-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 10, 'name' => 'U - до 200 км/год', 'slug' => 'is-u-do-200-kmch', 'language' => '*'];
        $columns[] = ['characteristic_id' => 6, 'name' => 'легковой', 'slug' => 'legkovoj', 'language' => 'ru'];
        $columns[] = ['characteristic_id' => 6, 'name' => 'легковий', 'slug' => 'legkovij', 'language' => 'ua'];
        $columns[] = ['characteristic_id' => 6, 'name' => 'внедорожник', 'slug' => 'vnedorozhnik', 'language' => 'ru'];
        $columns[] = ['characteristic_id' => 6, 'name' => 'позашляховик', 'slug' => 'pozashljahovik', 'language' => 'ua'];
        $columns[] = ['characteristic_id' => 6, 'name' => 'легкогрузовой', 'slug' => 'legko-gruzovoj', 'language' => 'ru'];
        $columns[] = ['characteristic_id' => 6, 'name' => 'легковантажний', 'slug' => 'legkovantazhnij', 'language' => 'ua'];
        $columns[] = ['characteristic_id' => 6, 'name' => 'грузовой', 'slug' => 'gruzovoj', 'language' => 'ru'];
        $columns[] = ['characteristic_id' => 6, 'name' => 'вантажний', 'slug' => 'vantazhnij', 'language' => 'ua'];
        $columns[] = ['characteristic_id' => 6, 'name' => 'спецтехника', 'slug' => 'spetstehnika', 'language' => 'ru'];
        $columns[] = ['characteristic_id' => 6, 'name' => 'спецтехніка', 'slug' => 'spectehnіka', 'language' => 'ua'];
        $columns[] = ['characteristic_id' => 7, 'name' => 'не шип', 'slug' => 'bez-shipa', 'language' => 'ru'];
        $columns[] = ['characteristic_id' => 7, 'name' => 'не шип', 'slug' => 'bez-shipa', 'language' => 'ua'];
        $columns[] = ['characteristic_id' => 7, 'name' => 'под шип', 'slug' => 'pod-ship', 'language' => 'ru'];
        $columns[] = ['characteristic_id' => 7, 'name' => 'під шип', 'slug' => 'pod-ship', 'language' => 'ua'];
        $columns[] = ['characteristic_id' => 7, 'name' => 'шип', 'slug' => 'ship', 'language' => 'ru'];
        $columns[] = ['characteristic_id' => 7, 'name' => 'шип', 'slug' => 'ship', 'language' => 'ua'];

        foreach ($columns as $colum => $dataTable) {
            DB::table((new CharacteristicValue())->getTable())->insert($dataTable);
        }

    }
}
